### PR TITLE
Add I/O for registration points

### LINKED ISSUE #451: Add support for 2D constraint points in GCP file IO
Currently reading/writing GCPs only handle the 3D points and 2D constraints are lost.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Enhance ground control point GeoJSON to also persist camera registration points. Fix some assorted related bugs.

Closes #451.

### CODE REVIEW

**Comment by borovik135** [comment]
Tested the functionality, and it works as expected, tnx.

**Review by mleotta — APPROVED** [review]
Look okay to me, but I have not tested.  @borovik135 can you test this and confirm that you can save GCPs, close TeleSculptor, reopen TeleSculptor and then reload your annotated 2D and 3D points?

**Comment by mleotta** [comment]
@borovik135 you read my mind.  If it works for you we can merge it.

**Comment by borovik135** [comment]
Annotated, computed camera, saved points, closed project, made sure JSON is fine, re-opened project, inspected 3D and 2D points, recomputed camera with same results, annotated another image, exported points, verified JSON, computed another camera. Both 3D and 2D pts seem to persist on project re-opening. Points do not seem to get saved automatically though: if one annotates without exporting points then closes the project, the new annotations will not appear in the JSON for the poitns.

**Comment by mleotta** [comment]
Yes, autosave is an issue that predates this PR.  We don't have a mechanism
for automatically (or even manually) saving parts of the project that are
interactively changed, like GCPs, 3D AOI, etc.  We can only save GCPs by
"exporting" them and then they become part of the project, which is not
very intuitive.  Any exported data should not get tied to the project file,
but a copy of the data should be automatically saved in the project file
when changed or when manually triggered through a "save project" option.
We don't have that now.

**Pull request merged**
