### PR TITLE
Show busy cursor while loading mesh

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**

### CODE REVIEW

**Comment by borovik135** [comment]
Confirming the busy mouse cursor display on mesh loading during opening a project. Alternative mesh import, when the project has already been opened, simply keeps the FileOpen dialog active till the mesh is actually loaded. That works for me, thanks.

**Comment by mwoehlke-kitware** [comment]
> simply keeps the FileOpen dialog active till the mesh is actually loaded

AFAIK, that is very difficult to do. The "normal" way one uses a file dialog is that it is gone by the time you get the path back. It *might* be possible to make this work, but it's a pile of code and requires using the dialog in a far more "hand-on" manner than the convenience `getOpenFileName` method.

**Comment by borovik135** [comment]
> > simply keeps the FileOpen dialog active till the mesh is actually loaded
> 
> AFAIK, that is very difficult to do. The "normal" way one uses a file dialog is that it is gone by the time you get the path back. It _might_ be possible to make this work, but it's a pile of code and requires using the dialog in a far more "hand-on" manner than the convenience `getOpenFileName` method.

Hanging FileOpen dialog is the behavior that I currently observe, which is fine, since it gets closed when the mesh has been loaded. I would say, the easier the better, as long as it makes sense: loading a new mesh via the "ImportMesh"  should display a busy cursor, if anything. It does not matter if the FileOpen dialog stays open/closed during the mesh loading. For instance, MeshLab or CloudCompare would display a progress bar on their status bars during mesh loading, which may be nice, but not required to land this branch, I think.

**Comment by mwoehlke-kitware** [comment]
> Hanging FileOpen dialog is the behavior that I currently observe

Oh, I see. This is probably because we haven't been back around the render loop yet to make it go away. If you *want* it to go away, that, I think, is easy; it should be just a matter of flushing the event queue before letting the VTK code to load the PLY take over.

A progress bar (at least, one that animates) isn't possible without more work, as it would require moving the PLY loading to a separate thread. IIUC we liked that idea but are punting for now due to the effort required. (I don't think it's *horrible*, but call it a couple hours...) An *actual* (i.e. meaningful) progress bar is probably not possible, as we don't have any way to my knowledge to get that information out of VTK.

**Comment by borovik135** [comment]
OK, let's forget about the mesh loading progress bar, at least for now, and stick to the busy cursor solution. I personally don't care much about the FileOpen dialog behavior in this case.

**Comment by mwoehlke-kitware** [comment]
Does this meet with your approval, then?

**Comment by borovik135** [comment]
I think we still need a busy cursor on the user requested mesh import, regardless of the FileOpen dialog behavior.

**Comment by mwoehlke-kitware** [comment]
> I think we still need a busy cursor on the user requested mesh import, regardless of the FileOpen dialog behavior.

That isn't working? The code to set the busy cursor is in `WorldView`; by the time we get there, we don't even know if we're loading from the project or from the dialog.

**Comment by borovik135** [comment]
OK, retested again now moving my mouse cursor away from the FileOpen dialog, and it does change to a busy cursor then. I think we can close this issue, thanks.

**Review by mleotta — APPROVED** [review]

**Pull request merged**
