### PR TITLE
Add icon to points with CRP on current frame

### LINKED ISSUE #453: Show which GCPs have a 2D point on the current frame
There is no indication of which 3D points (GCPs) have a corresponding 2D point for the current frame in the GCP panel.  We should add an icon or indicator of some type to show which GCPs have a 2D point on the active frame and then update those indicators as the active frame changes.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify `GroundControlPointsModel` to provide an icon on points which have a camera registration point on the active frame. Modify various bits to update the icons and active frame as needed. Simplify SVG for points that have been georegistered.

Closes #453.

### CODE REVIEW

**Comment by borovik135** [comment]
tested the capability: icons appear and disappear as prescribed; it would also be nice to know which frames have registration points, but that may be another PR?

**Comment by mleotta** [comment]
@mwoehlke-kitware I tested this branch.  The icons seem to work as expected, however, the CRPs in the camera view do not.  When I change the frame number the CRPs vanish as expected, but then when I come back to the previously annotate frame, the CRPs do not reappear in the camera view.  The GCP pane tells me that they still exist, but I don't see the cross hairs plotted at the previously selected point locations.

**Comment by mleotta** [comment]
By the way, this was tested on Windows by loading one of the AP Hill videos to provide images to click on.

**Comment by mleotta** [comment]
Merged into master this works.

**Pull request merged**
