### PR TITLE
fixed logger path in bash setup script

### PR DESCRIPTION
**Pull request by mleotta**

### CODE REVIEW

**Comment by russelldj** [comment]
It appears that the {build-dir}/external/telesculptor-build/setup_TeleSculptor.sh file is several days old, despite just rebuilding and installing. Is this expected behavior?

**Comment by mleotta** [comment]
You may need to manually re-run the CMake configuration step.  CMake generates that file at configure time.  Worst cast, you can delete that file in the build dir and force CMake to regenerate it.

**Comment by russelldj** [comment]
Interestingly, the new file seems to break things. Here is the expanded file I got. 

````
URR_DIR=`pwd`

export LD_LIBRARY_PATH=/home/david/dev/TeleSculptor/build/external/telesculptor-build/lib:$LD_LIBRARY_PATH

cd /home/david/dev/TeleSculptor/build/external/kwiver-build
source setup_KWIVER.sh
export KWIVER_CONFIG_PATH=$KWIVER_CONFIG_PATH:/home/david/dev/TeleSculptor/build/external/telesculptor-build/share/telesculptor/1.2.0/config
cd $CURR_DIR

export VITAL_LOGGER_FACTORY=$KWIVER_PLUGIN_PATH/logger/vital_log4cplus_logger
export LOG4CPLUS_CONFIGURATION=/home/david/dev/TeleSculptor/build/external/telesculptor-build/share/telesculptor/1.2.0/config/log4cplus.properties
````

However `source`ing this leads to `setup_KWIVER.sh: line 11: setup_KWIVER.sh: No such file or directory`. I think this is likely because I use `zsh` (which I believe is also the default on Mac) and I think this handles subshells differently, given that file is present in the specified directory.

**Review by russelldj — APPROVED** [review]

**Comment by russelldj** [comment]
In the future if I'm the last reviewer to approve should I simply merge changes?

**Comment by mleotta** [comment]
Yes, if the PR is not marked WIP and the CI tests have passed and you've been asked to review and you approve then you can merge it.

**Pull request merged**
