### PR TITLE
Replace "old" manual with RTD documentation

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove old, non-integrated tools for building the ReadTheDocs documentation and instead add this to the main CMake build system. This also replaces the "old" user manual. However, the latter is not yet removed, as we want to eventually fully integrate it with the RTD documentation.

### CODE REVIEW

**Comment by mleotta** [comment]
looks okay to me.  Let me test It will work on Windows.

**Review by mleotta — CHANGES_REQUESTED** [review]
I'm getting this error on Windows:

```
25>Generating user
25>Access is denied.
25>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'C:\Build\TeleSculptor\external\telesculptor-build\CMakeFiles\30fbf47507a712eda4865969ecf11d9d\user.rule;C:\Build\TeleSculptor\external\telesculptor-build\CMakeFiles\a48e85e7e21fb59bc4c998c1bf9115cf\manuals.rule' exited with code 5.
```

I'm not sure why

**Comment by mleotta** [comment]
This seem to be an issue with my sphinx installation.  I'm looking into it.

**Comment by mleotta** [comment]
Okay, it works on Windows, but in addition to sphinx, I also needed to `pip install sphinx_rtd_theme`, so we might want to add that to the build instructions.

**Comment by mwoehlke-kitware** [comment]
> I also needed to `pip install sphinx_rtd_theme`

Ah, right... same here.

**Pull request merged**
