### PR TITLE
Minor fixes to grammar, spacing, and spelling in README

### PR DESCRIPTION
**Pull request by OwenMcGee**
The change to line 124 is the most important, as it fixes an incorrect build instruction, whereas the other changes are just minor grammar fixes.

Edit: as well as the new dependency added on line 126

@chetnieter

### CODE REVIEW

**Review by mleotta — APPROVED** [review]

**Comment by willdunklin** [comment]
There is also a missing dependency for building Qt (xcb-xfixes). It can be installed with `sudo apt-get install libxcb-xfixes0-dev`

**Review by chetnieter — APPROVED** [review]

**Comment by chetnieter** [comment]
@mleotta Apparently I have write access for KWIVER but not TeleSculptor.

**Comment by mleotta** [comment]
@chetnieter See if you have write access now.

**Comment by chetnieter** [comment]
> @chetnieter See if you have write access now.

I do - thanks.

**Pull request merged**
