### PR TITLE
Overhaul camera calibration documentation and improve polish

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove unnecessary explicit emphasis markup from figure captions. Remove some leftover cruft and reduce warnings. Make the default text alignment 'justified'. Overhaul the "Manual Camera Calibration" section.

The updated version covers the same concepts but has been significantly rewritten using new features and to improve grammar and tone. Styling is introduced for menus, actions, shortcuts, and inline mathematical notation, and custom parsing to easily reference icons (the main feature from the old documentation system) has been added.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@borovik135, probably useful if you have time to take a look, also.

**Review by borovik135 — COMMENTED** [review]
The changes look OK to me. I would change Ctrl-Left click to Ctrl-PrimaryButton click to accommodate left-handed mouse users. Camera calibration involves the camera intrinsics + pose computation, which may need to be revealed a bit clearer, since the current version appears to emphasize the camera pose and barely mentions the camera intrinsics.

**Comment by mwoehlke-kitware** [comment]
>  I would change Ctrl-Left click to Ctrl-PrimaryButton click to accommodate left-handed mouse users.

Yeah, I sort of wondered about that. "Primary Button" is quite the mouthful, though. Do you think just "click" would be too obtuse?

**Comment by borovik135** [comment]
> > I would change Ctrl-Left click to Ctrl-PrimaryButton click to accommodate left-handed mouse users.
> 
> Yeah, I sort of wondered about that. "Primary Button" is quite the mouthful, though. Do you think just "click" would be too obtuse?

Ctrl-Click sounds fine to me.

**Comment by mleotta** [comment]
This is a good enhancement of the existing documentation.  I think we can merge it as it.

However, in reading through this it's clear that this calibration documentation is not well integrated into the rest of the documentation.  Sections on preparations, creating a new project, etc. are not specific to calibration and some of this is duplicated elsewhere in the docs. 

Now that have all this content in RTD format, it feels like we need to do an organizational overhaul, but that is outside the scope of this PR.

**Pull request merged**
